import Navbar from "@/components/Navbar/Navbar";
import Providers from "./Providers";
import "./globals.css";
import { Poppins } from "next/font/google";

import Sidebar from "@/components/Sidebar/Sidebar";
import { LoginModalStore } from "../../store/LoginModalStore";
import LoginModal from "@/components/Modals/LoginModal";

const poppins = Poppins({
  subsets: ["devanagari"],
  weight: "400",
});

export const metadata = {
  title: "Story",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Navbar />
          <LoginModal />
          <div className="flex relative mt-20">
            {children}

            <Sidebar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
