import Navbar from "@/components/Navbar/Navbar";
import Providers from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import CategoryBar from "@/components/CategoryBar/CategoryBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <CategoryBar /> 
          {children}
        </Providers>
      </body>
    </html>
  );
}
